### ISSUE TITLE
Problem with method buildConfingField()

### ISSUE THREAD

**Issue by bvb0995** [hikikomoriphoenix/GameHunter#41]
Could you help me please? I have this error

ERROR: Could not find method buildConfigField() for arguments [String, BuildType_Decorated{name=giantbomb_api_key, debuggable=false, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=false, zipAlignEnabled=true, signingConfig=null, embedMicroApp=true, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}}, "9a2f9d8c12ba38e7a3cffc2530bff1b967d1a5a5"] on BuildType_Decorated{name=debug, debuggable=true, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=false, zipAlignEnabled=true, signingConfig=SigningConfig_Decorated{name=debug, storeFile=C:\Users\ullah\.android\debug.keystore, storePassword=android, keyAlias=AndroidDebugKey, keyPassword=android, storeType=C:\Users\ullah\.android\debug.keystore, v1SigningEnabled=true, v2SigningEnabled=true}, embedMicroApp=false, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.BuildType.

**Comment by hikikomoriphoenix** [comment]
You need to get your own api key from Giant bomb [here](https://www.giantbomb.com/api/)
Then go to .gradle folder in your Users directory in Windows or Home directory in Linux. Create gradle.properties file and add this line:

`giantbomb_api_key="insert your api key here"`

Save.
This is your global properties file. No one can see this but you.
